# Generated by Django 4.2.7 on 2023-11-19 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='doctor',
        ),
    ]
