# Generated by Django 4.2.7 on 2023-11-19 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_payments_delete_location_delete_payment'),
        ('chat', '0002_remove_chatmessage_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='users.user'),
        ),
    ]
