# Generated by Django 4.2.7 on 2023-11-15 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoradditionaldetails',
            name='available_times',
        ),
    ]
