# Generated by Django 4.2.7 on 2023-11-16 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_remove_doctoradditionaldetails_available_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorslot',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot', to='doctors.doctorinfo'),
        ),
    ]
