# Generated by Django 4.2.7 on 2023-11-18 03:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_doctorslot_doctor'),
        ('users', '0003_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField(default='00:00:05')),
                ('end_time', models.TimeField(default='00:00:05')),
                ('documents', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('payment', models.BooleanField(default=False)),
                ('amount', models.IntegerField()),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='doctors.doctorinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
