# Generated by Django 4.2.7 on 2023-11-28 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_useraddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
