# Generated by Django 4.2.7 on 2023-11-28 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_payments_doctor_slot'),
    ]

    operations = [
    ]
